#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Sep 26 16:21:43 PDT 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim multi3_tb_behav -key {Behavioral:sim_1:Functional:multi3_tb} -tclbatch multi3_tb.tcl -log simulate.log"
xsim multi3_tb_behav -key {Behavioral:sim_1:Functional:multi3_tb} -tclbatch multi3_tb.tcl -log simulate.log

